# Generated by Django 3.0.3 on 2020-05-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resorts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('base', models.IntegerField()),
                ('adult', models.IntegerField()),
                ('child', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1200)),
                ('rating', models.IntegerField()),
                ('phone', models.CharField(max_length=20)),
                ('picurl', models.CharField(max_length=100)),
            ],
        ),
    ]
