# Generated by Django 3.0.3 on 2020-05-02 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookDate', models.DateField()),
                ('adult', models.IntegerField()),
                ('child', models.IntegerField()),
                ('total', models.IntegerField()),
                ('resortname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resortname', to='mainapp.Resorts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
